# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0020_thrusters'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('batteries', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.Batteries')),
                ('chassis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.Chassis')),
                ('commDish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.CommDish')),
                ('fuelTank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.FuelTank')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.Processor')),
                ('sensors', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.Sensors')),
                ('solarPanels', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.SolarPanels')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.Storage')),
                ('thrusters', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.Thrusters')),
            ],
        ),
    ]
