# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160524_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
