# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_siteuser_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Commercial'), (2, 'Criminal'), (3, 'Government'), (4, 'Non-Profit'), (5, 'Science')])),
                ('payment', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.SiteUser')),
            ],
        ),
    ]
