# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='phi',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='job',
            name='theta',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=6),
        ),
    ]
