# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20160603_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_space',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=2),
        ),
        migrations.AddField(
            model_name='job',
            name='required_speed',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=2),
        ),
    ]
