# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20160929_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Expired'), (3, 'Rejected'), (4, 'In Progress'), (5, 'Complete')], default=1),
        ),
    ]
