# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-06 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Job'),
        ),
    ]
