# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('width', models.SmallIntegerField()),
                ('length', models.SmallIntegerField()),
                ('height', models.SmallIntegerField()),
            ],
        ),
    ]
