# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_auto_20160514_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='durability',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='chassis',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
