# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20160514_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dish_color', models.CharField(max_length=7)),
                ('bulb_color', models.CharField(max_length=7)),
                ('dish_width', models.SmallIntegerField()),
                ('cost', models.SmallIntegerField(default=0)),
                ('description', models.TextField(default='No description')),
                ('comp_type', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='components.ComponentType')),
            ],
        ),
    ]
