# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_commdish_signal_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='commdish',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=2),
        ),
    ]
