# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_auto_20160515_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chassis',
            name='comp_type',
        ),
        migrations.RemoveField(
            model_name='chassis',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='chassis',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chassis',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chassis',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='commdish',
            name='comp_type',
        ),
        migrations.RemoveField(
            model_name='commdish',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='commdish',
            name='description',
        ),
        migrations.RemoveField(
            model_name='commdish',
            name='name',
        ),
        migrations.RemoveField(
            model_name='commdish',
            name='weight',
        ),
    ]
