# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_auto_20160515_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='chassis',
            name='comp_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='type', to='components.ComponentType'),
        ),
        migrations.AddField(
            model_name='chassis',
            name='cost',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chassis',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='chassis',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chassis',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='commdish',
            name='comp_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='type', to='components.ComponentType'),
        ),
        migrations.AddField(
            model_name='commdish',
            name='cost',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commdish',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='commdish',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commdish',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
