# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0012_auto_20160515_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chassis',
            name='comp_type',
        ),
        migrations.RemoveField(
            model_name='commdish',
            name='comp_type',
        ),
        migrations.AddField(
            model_name='componenttype',
            name='total',
            field=models.SmallIntegerField(default=0),
        ),
    ]
